name: MLflow CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"
        activate-environment: base

    - name: Verify conda
      run: |
        conda --version
        python --version

    - name: Install MLflow
      run: |
        pip install --upgrade pip
        pip install mlflow

    - name: Run MLflow project (conda)
      run: |
        cd MLProject
        mlflow run . --env-manager=conda

    - name: Debug mlruns
      run: |
        cd MLProject
        find mlruns -maxdepth 3 -type d

    - name: Upload MLflow artifacts to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
        filename: MLProject/mlruns
        folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
        name: "hotel-bookings-prediction_run${{ github.run_id }}"
        overwrite: "true"
        mirrorDirectoryStructure: "true"

    - name: Get latest MLflow run id
      run: |
        cd MLProject
        RUN_ID=$(ls -d mlruns/0/*/ | grep -v models | tail -n 1 | xargs -r basename)
        if [ -z "$RUN_ID" ]; then
          echo "No MLflow run found"
          exit 1
        fi
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Docker Hub Log in
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Model
      run: |
        cd MLProject
        mlflow models build-docker \
          -m runs:/$RUN_ID/model \
          -n ${{ secrets.DOCKERHUB_USERNAME }}/hotel-bookings-prediction

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hotel-bookings-prediction

    - name: Complete job
      run: echo "Pipeline finished successfully"
